// <auto-generated />
using System;
using Data.Repository.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Repository.Implementations.Migrations
{
    [DbContext(typeof(MultibancaDBContext))]
    [Migration("20260508192614_Implement_AntecCred_DatosComer")]
    partial class Implement_AntecCred_DatosComer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.FuncTransversal.bitacora_entity", b =>
                {
                    b.Property<long>("id_bitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id_bitacora"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fecha_alta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("id_actividad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("id_bitacora");

                    b.ToTable("bitacora", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.FuncTransversal.expediente_digital_entity", b =>
                {
                    b.Property<long>("id_archivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id_archivo"));

                    b.Property<string>("comentarios")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("fecha_alta")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("id_documento")
                        .HasColumnType("integer");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<int?>("id_usuario")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("nombre_archivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre_archivo_original")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.Property<int>("version_archivo")
                        .HasColumnType("integer");

                    b.HasKey("id_archivo");

                    b.ToTable("expediente_digital", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.CargaOperacionBanco.carga_operacion_banco_antecedente_comprador_entity", b =>
                {
                    b.Property<int>("id_carga_operacion_banco_antecedente_comprador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco_antecedente_comprador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_carga_operacion_banco_antecedente_comprador"));

                    b.Property<string>("apellido_materno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("apellido_paterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("comuna")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("comuna");

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("estado_civil")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_civil");

                    b.Property<DateTime?>("fecha_nacimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("genero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("genero");

                    b.Property<int>("id_carga_operacion_banco")
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_expediente");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("nacionalidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("nombres")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombres");

                    b.Property<string>("profesion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("profesion");

                    b.Property<string>("razon_social")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("razon_social");

                    b.Property<string>("region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("relacion_titular")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relacion_titular");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean")
                        .HasColumnName("row_status");

                    b.Property<string>("rut")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("rut");

                    b.Property<string>("telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("tipo_comprador")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_comprador");

                    b.HasKey("id_carga_operacion_banco_antecedente_comprador");

                    b.HasIndex("id_carga_operacion_banco")
                        .HasDatabaseName("ix_cob_antecedente_comprador_id_carga_operacion_banco");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_cob_antecedente_comprador_id_expediente");

                    b.HasIndex("rut")
                        .HasDatabaseName("ix_cob_antecedente_comprador_rut");

                    b.ToTable("carga_operacion_banco_antecedente_comprador", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.CargaOperacionBanco.carga_operacion_banco_antecedente_credito_entity", b =>
                {
                    b.Property<int>("id_carga_operacion_banco_antecedente_credito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco_antecedente_credito");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_carga_operacion_banco_antecedente_credito"));

                    b.Property<int?>("cantidad_meses_sin_vencimiento")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_meses_sin_vencimiento");

                    b.Property<string>("codigo_producto_cartera")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_producto_cartera");

                    b.Property<decimal?>("comision")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("comision");

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("destino_credito")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("destino_credito");

                    b.Property<decimal?>("factor_conversion_uf")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("factor_conversion_uf");

                    b.Property<DateTime?>("fecha_inicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("id_carga_operacion_banco")
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_expediente");

                    b.Property<int?>("indicador_cred_comp")
                        .HasColumnType("integer")
                        .HasColumnName("indicador_cred_comp");

                    b.Property<string>("indicador_pac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("indicador_pac");

                    b.Property<string>("indicador_segunda_vivienda")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("indicador_segunda_vivienda");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("meses_sabaticos")
                        .HasColumnType("integer")
                        .HasColumnName("meses_sabaticos");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("moneda")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("moneda");

                    b.Property<decimal?>("monto_nominal")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("monto_nominal");

                    b.Property<decimal?>("monto_residual")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("monto_residual");

                    b.Property<decimal?>("monto_solicitado")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("monto_solicitado");

                    b.Property<long?>("numero_cuenta_gastos")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_cuenta_gastos");

                    b.Property<int?>("periodo_gracia")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_gracia");

                    b.Property<int?>("plazo")
                        .HasColumnType("integer")
                        .HasColumnName("plazo");

                    b.Property<int?>("plazo_primer_periodo")
                        .HasColumnType("integer")
                        .HasColumnName("plazo_primer_periodo");

                    b.Property<int?>("plazo_segundo_periodo")
                        .HasColumnType("integer")
                        .HasColumnName("plazo_segundo_periodo");

                    b.Property<string>("precio_venta_moneda_original")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("precio_venta_moneda_original");

                    b.Property<decimal?>("precio_venta_pesos")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("precio_venta_pesos");

                    b.Property<decimal?>("prestamo_maximo")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("prestamo_maximo");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean")
                        .HasColumnName("row_status");

                    b.Property<decimal?>("tasa")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("tasa");

                    b.Property<decimal?>("tasa_maxima")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("tasa_maxima");

                    b.Property<decimal?>("tasa_primer_periodo")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("tasa_primer_periodo");

                    b.Property<decimal?>("tasa_segundo_periodo")
                        .HasColumnType("numeric(18, 6)")
                        .HasColumnName("tasa_segundo_periodo");

                    b.Property<string>("tipo_financiamiento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_financiamiento");

                    b.Property<string>("tipo_prestamo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_prestamo");

                    b.Property<string>("tipo_tasa")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_tasa");

                    b.Property<string>("tipo_tasa_aplic_contab")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_tasa_aplic_contab");

                    b.Property<string>("tipo_tasa_mixta_prod_com")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_tasa_mixta_prod_com");

                    b.Property<string>("variabilidad_tasa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("variabilidad_tasa");

                    b.HasKey("id_carga_operacion_banco_antecedente_credito");

                    b.HasIndex("id_carga_operacion_banco")
                        .HasDatabaseName("ix_cob_ant_credito_id_carga_operacion_banco");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_cob_ant_credito_id_expediente");

                    b.ToTable("carga_operacion_banco_antecedente_credito", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.CargaOperacionBanco.carga_operacion_banco_antecedente_vendedor_entity", b =>
                {
                    b.Property<int>("id_carga_operacion_banco_antecedente_vendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco_antecedente_vendedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_carga_operacion_banco_antecedente_vendedor"));

                    b.Property<string>("apellido_materno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("apellido_paterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("comuna")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("comuna");

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("estado_civil")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_civil");

                    b.Property<DateTime?>("fecha_nacimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("genero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("genero");

                    b.Property<int>("id_carga_operacion_banco")
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_expediente");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("nacionalidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("nombres")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombres");

                    b.Property<string>("profesion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("profesion");

                    b.Property<string>("razon_social")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("razon_social");

                    b.Property<string>("region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("relacion_titular")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relacion_titular");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean")
                        .HasColumnName("row_status");

                    b.Property<string>("rut")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("rut");

                    b.Property<string>("telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("tipo_vendedor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_vendedor");

                    b.HasKey("id_carga_operacion_banco_antecedente_vendedor");

                    b.HasIndex("id_carga_operacion_banco")
                        .HasDatabaseName("ix_cob_antecedente_vendedor_id_carga_operacion_banco");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_cob_antecedente_vendedor_id_expediente");

                    b.HasIndex("rut")
                        .HasDatabaseName("ix_cob_antecedente_vendedor_rut");

                    b.ToTable("carga_operacion_banco_antecedente_vendedor", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.CargaOperacionBanco.carga_operacion_banco_datos_comercial_entity", b =>
                {
                    b.Property<int>("id_carga_operacion_banco_datos_comercial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco_datos_comercial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_carga_operacion_banco_datos_comercial"));

                    b.Property<long?>("codigo_curse")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo_curse");

                    b.Property<long?>("codigo_ejecutivo")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo_ejecutivo");

                    b.Property<long?>("codigo_ejecutivo_curse")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo_ejecutivo_curse");

                    b.Property<long?>("codigo_oficina")
                        .HasColumnType("bigint")
                        .HasColumnName("codigo_oficina");

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("glosa_curse")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("glosa_curse");

                    b.Property<int>("id_carga_operacion_banco")
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_expediente");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("login_ejecutivo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login_ejecutivo");

                    b.Property<string>("login_ejecutivo_curse")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login_ejecutivo_curse");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("nombre_banco")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_banco");

                    b.Property<string>("nombre_ejecutivo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_ejecutivo");

                    b.Property<string>("nombre_ejecutivo_curse")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_ejecutivo_curse");

                    b.Property<string>("nombre_oficina")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_oficina");

                    b.Property<string>("renovacion_urbana")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("renovacion_urbana");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean")
                        .HasColumnName("row_status");

                    b.Property<long?>("rut_banco")
                        .HasColumnType("bigint")
                        .HasColumnName("rut_banco");

                    b.Property<long?>("rut_ejecutivo")
                        .HasColumnType("bigint")
                        .HasColumnName("rut_ejecutivo");

                    b.Property<long?>("rut_ejecutivo_curse")
                        .HasColumnType("bigint")
                        .HasColumnName("rut_ejecutivo_curse");

                    b.Property<string>("tipo_hipoteca")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tipo_hipoteca");

                    b.HasKey("id_carga_operacion_banco_datos_comercial");

                    b.HasIndex("id_carga_operacion_banco")
                        .HasDatabaseName("ix_cob_datos_comercial_id_carga_operacion_banco");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_cob_datos_comercial_id_expediente");

                    b.ToTable("carga_operacion_banco_datos_comercial", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.CargaOperacionBanco.carga_operacion_banco_datos_operacion_entity", b =>
                {
                    b.Property<int>("id_carga_operacion_banco_datos_operacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco_datos_operacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_carga_operacion_banco_datos_operacion"));

                    b.Property<string>("canal_venta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("canal_venta");

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("glosa_producto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("glosa_producto");

                    b.Property<int>("id_carga_operacion_banco")
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_expediente");

                    b.Property<string>("inmobiliaria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inmobiliaria");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("modelo_operacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modelo_operacion");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_date");

                    b.Property<long?>("nro_mutuo")
                        .HasColumnType("bigint")
                        .HasColumnName("nro_mutuo");

                    b.Property<long?>("nro_op_cartera")
                        .HasColumnType("bigint")
                        .HasColumnName("nro_op_cartera");

                    b.Property<long?>("nro_registro")
                        .HasColumnType("bigint")
                        .HasColumnName("nro_registro");

                    b.Property<string>("propietario")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("propietario");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean")
                        .HasColumnName("row_status");

                    b.Property<string>("segmento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("segmento");

                    b.Property<string>("tipo_carpeta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_carpeta");

                    b.Property<string>("tipo_operacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_operacion");

                    b.Property<string>("ult_clasif_al")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ult_clasif_al");

                    b.HasKey("id_carga_operacion_banco_datos_operacion");

                    b.HasIndex("id_carga_operacion_banco")
                        .HasDatabaseName("ix_cob_datos_operacion_id_carga_operacion_banco");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_cob_datos_operacion_id_expediente");

                    b.ToTable("carga_operacion_banco_datos_operacion", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.CargaOperacionBanco.carga_operacion_banco_entity", b =>
                {
                    b.Property<int>("id_carga_operacion_banco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_carga_operacion_banco"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_expediente");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_date");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean")
                        .HasColumnName("row_status");

                    b.HasKey("id_carga_operacion_banco");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_carga_operacion_banco_id_expediente");

                    b.ToTable("carga_operacion_banco", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.actividades_entity", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_alta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_asignacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_cancelacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_inicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_reactivacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_reingreso")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_suspencion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_termino")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("id_actividad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<long>("id_rol")
                        .HasColumnType("bigint");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("actividades", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.corregir_reparo_fabrica_entity", b =>
                {
                    b.Property<int>("id_corregir_reparo_fabrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_corregir_reparo_fabrica"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<int>("id_usuario_solicitante")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_subsanar")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("id_corregir_reparo_fabrica");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_corregir_reparo_fabrica_expediente");

                    b.ToTable("corregir_reparo_fabrica", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.recepcion_carga_fabrica_entity", b =>
                {
                    b.Property<int>("id_recepcion_carga_fabrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_recepcion_carga_fabrica"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<int>("id_usuario_solicitante")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_enviar_reparo")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("id_recepcion_carga_fabrica");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_recepcion_carga_fabrica_expediente");

                    b.ToTable("recepcion_carga_fabrica", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.menus_entity", b =>
                {
                    b.Property<int>("menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("menu_id"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description_alt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("icon_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_show_home_menu")
                        .IsRequired()
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_show_navbar")
                        .IsRequired()
                        .HasColumnType("boolean");

                    b.Property<int?>("menu_padre_id")
                        .HasColumnType("integer");

                    b.Property<string>("menu_url")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("orden")
                        .HasColumnType("integer");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("menu_id");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.role_menu_entity", b =>
                {
                    b.Property<int>("role_menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("role_menu_id"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int>("menu_id")
                        .HasColumnType("integer");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("role_menu_id");

                    b.HasIndex("menu_id");

                    b.HasIndex("role_id");

                    b.ToTable("role_menu", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.roles_entity", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("role_id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("role_id");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.users_entity", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("id_document_type")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_first_access")
                        .HasColumnType("boolean");

                    b.Property<string>("last_name_first")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("last_name_second")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nro_document")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("remaining_attempts")
                        .HasColumnType("integer");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("user_id");

                    b.HasIndex("role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.role_menu_entity", b =>
                {
                    b.HasOne("Data.Repository.Interfaces.Entities.Security.menus_entity", "menu")
                        .WithMany("role_menus")
                        .HasForeignKey("menu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Repository.Interfaces.Entities.Security.roles_entity", "role")
                        .WithMany("role_menus")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");

                    b.Navigation("role");
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.users_entity", b =>
                {
                    b.HasOne("Data.Repository.Interfaces.Entities.Security.roles_entity", "role")
                        .WithMany("users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.menus_entity", b =>
                {
                    b.Navigation("role_menus");
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.roles_entity", b =>
                {
                    b.Navigation("role_menus");

                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
