// <auto-generated />
using System;
using Data.Repository.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Repository.Implementations.Migrations
{
    [DbContext(typeof(MultibancaDBContext))]
    [Migration("20260623120000_AddCargarDocumentosCliente")]
    partial class AddCargarDocumentosCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Multibanca.Domain.Models.Multibanca.BBVA.cargar_documentos_cliente", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("documentos_adjuntos")
                        .HasColumnType("boolean")
                        .HasColumnName("documentos_adjuntos");

                    b.Property<string>("id_actividad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_actividad");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_expediente");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean")
                        .HasColumnName("row_status");

                    b.HasKey("id");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("IX_cargar_docs_cliente_expediente");

                    b.ToTable("cargar_documentos_cliente", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
