// <auto-generated />
using System;
using Data.Repository.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Repository.Implementations.Migrations
{
    [DbContext(typeof(MultibancaDBContext))]
    [Migration("20260506162641_AddDatosCredito")]
    partial class AddDatosCredito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.FuncTransversal.bitacora_entity", b =>
                {
                    b.Property<long>("id_bitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id_bitacora"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fecha_alta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("id_actividad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("id_bitacora");

                    b.ToTable("bitacora", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.FuncTransversal.expediente_digital_entity", b =>
                {
                    b.Property<long>("id_archivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id_archivo"));

                    b.Property<string>("comentarios")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("fecha_alta")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("id_documento")
                        .HasColumnType("integer");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<int?>("id_usuario")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("nombre_archivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre_archivo_original")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.Property<int>("version_archivo")
                        .HasColumnType("integer");

                    b.HasKey("id_archivo");

                    b.ToTable("expediente_digital", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.actividades_entity", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_alta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_asignacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_cancelacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_inicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_reactivacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_reingreso")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_suspencion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_termino")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("id_actividad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<long>("id_rol")
                        .HasColumnType("bigint");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("actividades", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.datos_credito_entity", b =>
                {
                    b.Property<int>("id_datos_credito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_datos_credito"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("credito_segunda_vivienda")
                        .HasColumnType("boolean");

                    b.Property<bool?>("dfl2")
                        .HasColumnType("boolean");

                    b.Property<bool?>("enviar_a_reparo")
                        .HasColumnType("boolean");

                    b.Property<bool?>("fines_generales")
                        .HasColumnType("boolean");

                    b.Property<string>("id_actividad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<int?>("id_tipo_operacion")
                        .HasColumnType("integer");

                    b.Property<decimal?>("impuesto_a_pagar")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("inmobiliaria")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("monto_credito_afecto_impuesto")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("nombre_proyecto")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("porcentaje_impuesto")
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool?>("propietario_dfl2")
                        .HasColumnType("boolean");

                    b.Property<bool?>("recepcion_final_mayor_2_anios")
                        .HasColumnType("boolean");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.Property<string>("ubicacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("vivienda_social")
                        .HasColumnType("boolean");

                    b.HasKey("id_datos_credito");

                    b.HasIndex("id_expediente");

                    b.ToTable("datos_credito", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.menus_entity", b =>
                {
                    b.Property<int>("menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("menu_id"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description_alt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("icon_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_show_home_menu")
                        .IsRequired()
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_show_navbar")
                        .IsRequired()
                        .HasColumnType("boolean");

                    b.Property<int?>("menu_padre_id")
                        .HasColumnType("integer");

                    b.Property<string>("menu_url")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("orden")
                        .HasColumnType("integer");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("menu_id");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.role_menu_entity", b =>
                {
                    b.Property<int>("role_menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("role_menu_id"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int>("menu_id")
                        .HasColumnType("integer");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("role_menu_id");

                    b.HasIndex("menu_id");

                    b.HasIndex("role_id");

                    b.ToTable("role_menu", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.roles_entity", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("role_id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("role_id");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.users_entity", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("id_document_type")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_first_access")
                        .HasColumnType("boolean");

                    b.Property<string>("last_name_first")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("last_name_second")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nro_document")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("remaining_attempts")
                        .HasColumnType("integer");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("user_id");

                    b.HasIndex("role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.role_menu_entity", b =>
                {
                    b.HasOne("Data.Repository.Interfaces.Entities.Security.menus_entity", "menu")
                        .WithMany("role_menus")
                        .HasForeignKey("menu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Repository.Interfaces.Entities.Security.roles_entity", "role")
                        .WithMany("role_menus")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");

                    b.Navigation("role");
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.users_entity", b =>
                {
                    b.HasOne("Data.Repository.Interfaces.Entities.Security.roles_entity", "role")
                        .WithMany("users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.menus_entity", b =>
                {
                    b.Navigation("role_menus");
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.roles_entity", b =>
                {
                    b.Navigation("role_menus");

                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
