using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Repository.Implementations.Migrations
{
    /// <inheritdoc />
    public partial class Implement_AprobacionComercialLegalCdR : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS aprobacion_comercial_legal_cdr (
                    id_aprobacion_comercial_legal_cdr integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    id_expediente bigint NOT NULL,
                    enviar_a_reparo boolean NOT NULL,
                    observaciones character varying(2000),
                    is_active boolean NOT NULL,
                    row_status boolean NOT NULL,
                    created_by integer NOT NULL,
                    created_date timestamp without time zone NOT NULL,
                    modified_by integer,
                    modified_date timestamp without time zone
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ix_aprobacion_comercial_legal_cdr
                ON aprobacion_comercial_legal_cdr (id_expediente);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "aprobacion_comercial_legal_cdr");
        }
    }
}
