// <auto-generated />
using System;
using Data.Repository.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Repository.Implementations.Migrations
{
    [DbContext(typeof(MultibancaDBContext))]
    [Migration("20260508182016_Impleent_Antecedendes_Vendedor")]
    partial class Impleent_Antecedendes_Vendedor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.FuncTransversal.bitacora_entity", b =>
                {
                    b.Property<long>("id_bitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id_bitacora"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fecha_alta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("id_actividad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("id_bitacora");

                    b.ToTable("bitacora", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.FuncTransversal.expediente_digital_entity", b =>
                {
                    b.Property<long>("id_archivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id_archivo"));

                    b.Property<string>("comentarios")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("fecha_alta")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("id_documento")
                        .HasColumnType("integer");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<int?>("id_usuario")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("nombre_archivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre_archivo_original")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.Property<int>("version_archivo")
                        .HasColumnType("integer");

                    b.HasKey("id_archivo");

                    b.ToTable("expediente_digital", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.CargaOperacionBanco.carga_operacion_banco_antecedente_comprador_entity", b =>
                {
                    b.Property<int>("id_carga_operacion_banco_antecedente_comprador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco_antecedente_comprador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_carga_operacion_banco_antecedente_comprador"));

                    b.Property<string>("apellido_materno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("apellido_paterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("comuna")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("comuna");

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("estado_civil")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_civil");

                    b.Property<DateTime?>("fecha_nacimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("genero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("genero");

                    b.Property<int>("id_carga_operacion_banco")
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_expediente");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("nacionalidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("nombres")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombres");

                    b.Property<string>("profesion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("profesion");

                    b.Property<string>("razon_social")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("razon_social");

                    b.Property<string>("region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("relacion_titular")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relacion_titular");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean")
                        .HasColumnName("row_status");

                    b.Property<string>("rut")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("rut");

                    b.Property<string>("telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("tipo_comprador")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_comprador");

                    b.HasKey("id_carga_operacion_banco_antecedente_comprador");

                    b.HasIndex("id_carga_operacion_banco")
                        .HasDatabaseName("ix_cob_antecedente_comprador_id_carga_operacion_banco");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_cob_antecedente_comprador_id_expediente");

                    b.HasIndex("rut")
                        .HasDatabaseName("ix_cob_antecedente_comprador_rut");

                    b.ToTable("carga_operacion_banco_antecedente_comprador", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.CargaOperacionBanco.carga_operacion_banco_antecedente_vendedor_entity", b =>
                {
                    b.Property<int>("id_carga_operacion_banco_antecedente_vendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco_antecedente_vendedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_carga_operacion_banco_antecedente_vendedor"));

                    b.Property<string>("apellido_materno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("apellido_paterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("comuna")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("comuna");

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("estado_civil")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_civil");

                    b.Property<DateTime?>("fecha_nacimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("genero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("genero");

                    b.Property<int>("id_carga_operacion_banco")
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_expediente");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("nacionalidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("nombres")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombres");

                    b.Property<string>("profesion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("profesion");

                    b.Property<string>("razon_social")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("razon_social");

                    b.Property<string>("region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("relacion_titular")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relacion_titular");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean")
                        .HasColumnName("row_status");

                    b.Property<string>("rut")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("rut");

                    b.Property<string>("telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("tipo_vendedor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_vendedor");

                    b.HasKey("id_carga_operacion_banco_antecedente_vendedor");

                    b.HasIndex("id_carga_operacion_banco")
                        .HasDatabaseName("ix_cob_antecedente_vendedor_id_carga_operacion_banco");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_cob_antecedente_vendedor_id_expediente");

                    b.HasIndex("rut")
                        .HasDatabaseName("ix_cob_antecedente_vendedor_rut");

                    b.ToTable("carga_operacion_banco_antecedente_vendedor", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.CargaOperacionBanco.carga_operacion_banco_datos_operacion_entity", b =>
                {
                    b.Property<int>("id_carga_operacion_banco_datos_operacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco_datos_operacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_carga_operacion_banco_datos_operacion"));

                    b.Property<string>("canal_venta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("canal_venta");

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("glosa_producto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("glosa_producto");

                    b.Property<int>("id_carga_operacion_banco")
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_expediente");

                    b.Property<string>("inmobiliaria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inmobiliaria");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("modelo_operacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modelo_operacion");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_date");

                    b.Property<long?>("nro_mutuo")
                        .HasColumnType("bigint")
                        .HasColumnName("nro_mutuo");

                    b.Property<long?>("nro_op_cartera")
                        .HasColumnType("bigint")
                        .HasColumnName("nro_op_cartera");

                    b.Property<long?>("nro_registro")
                        .HasColumnType("bigint")
                        .HasColumnName("nro_registro");

                    b.Property<string>("propietario")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("propietario");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean")
                        .HasColumnName("row_status");

                    b.Property<string>("segmento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("segmento");

                    b.Property<string>("tipo_carpeta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_carpeta");

                    b.Property<string>("tipo_operacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_operacion");

                    b.Property<string>("ult_clasif_al")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ult_clasif_al");

                    b.HasKey("id_carga_operacion_banco_datos_operacion");

                    b.HasIndex("id_carga_operacion_banco")
                        .HasDatabaseName("ix_cob_datos_operacion_id_carga_operacion_banco");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_cob_datos_operacion_id_expediente");

                    b.ToTable("carga_operacion_banco_datos_operacion", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.CargaOperacionBanco.carga_operacion_banco_entity", b =>
                {
                    b.Property<int>("id_carga_operacion_banco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carga_operacion_banco");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_carga_operacion_banco"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_expediente");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_date");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean")
                        .HasColumnName("row_status");

                    b.HasKey("id_carga_operacion_banco");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_carga_operacion_banco_id_expediente");

                    b.ToTable("carga_operacion_banco", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.actividades_entity", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_alta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_asignacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_cancelacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_inicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_reactivacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_reingreso")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_suspencion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("fecha_termino")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("id_actividad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<long>("id_rol")
                        .HasColumnType("bigint");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("actividades", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.corregir_reparo_fabrica_entity", b =>
                {
                    b.Property<int>("id_corregir_reparo_fabrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_corregir_reparo_fabrica"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<int>("id_usuario_solicitante")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_subsanar")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("id_corregir_reparo_fabrica");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_corregir_reparo_fabrica_expediente");

                    b.ToTable("corregir_reparo_fabrica", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Multibanca.recepcion_carga_fabrica_entity", b =>
                {
                    b.Property<int>("id_recepcion_carga_fabrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_recepcion_carga_fabrica"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("id_expediente")
                        .HasColumnType("bigint");

                    b.Property<int>("id_usuario_solicitante")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_enviar_reparo")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("id_recepcion_carga_fabrica");

                    b.HasIndex("id_expediente")
                        .HasDatabaseName("ix_recepcion_carga_fabrica_expediente");

                    b.ToTable("recepcion_carga_fabrica", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.menus_entity", b =>
                {
                    b.Property<int>("menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("menu_id"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description_alt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("icon_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_show_home_menu")
                        .IsRequired()
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_show_navbar")
                        .IsRequired()
                        .HasColumnType("boolean");

                    b.Property<int?>("menu_padre_id")
                        .HasColumnType("integer");

                    b.Property<string>("menu_url")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("orden")
                        .HasColumnType("integer");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("menu_id");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.role_menu_entity", b =>
                {
                    b.Property<int>("role_menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("role_menu_id"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int>("menu_id")
                        .HasColumnType("integer");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("role_menu_id");

                    b.HasIndex("menu_id");

                    b.HasIndex("role_id");

                    b.ToTable("role_menu", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.roles_entity", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("role_id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.HasKey("role_id");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.users_entity", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("id_document_type")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool?>("is_first_access")
                        .HasColumnType("boolean");

                    b.Property<string>("last_name_first")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("last_name_second")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("modified_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nro_document")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("remaining_attempts")
                        .HasColumnType("integer");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<bool>("row_status")
                        .HasColumnType("boolean");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("user_id");

                    b.HasIndex("role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.role_menu_entity", b =>
                {
                    b.HasOne("Data.Repository.Interfaces.Entities.Security.menus_entity", "menu")
                        .WithMany("role_menus")
                        .HasForeignKey("menu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Repository.Interfaces.Entities.Security.roles_entity", "role")
                        .WithMany("role_menus")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");

                    b.Navigation("role");
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.users_entity", b =>
                {
                    b.HasOne("Data.Repository.Interfaces.Entities.Security.roles_entity", "role")
                        .WithMany("users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.menus_entity", b =>
                {
                    b.Navigation("role_menus");
                });

            modelBuilder.Entity("Data.Repository.Interfaces.Entities.Security.roles_entity", b =>
                {
                    b.Navigation("role_menus");

                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
