using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Repository.Implementations.Migrations
{
    /// <inheritdoc />
    public partial class AddCargarDocumentosConstructora : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE public.carga_operacion_banco_datos_operacion
                    ADD COLUMN IF NOT EXISTS canal_originacion character varying(50),
                    ADD COLUMN IF NOT EXISTS codigo_asesor character varying(50),
                    ADD COLUMN IF NOT EXISTS codigo_oficina character varying(20),
                    ADD COLUMN IF NOT EXISTS codigo_proyecto character varying(50),
                    ADD COLUMN IF NOT EXISTS descripcion_oficina character varying(200),
                    ADD COLUMN IF NOT EXISTS descripcion_proyecto character varying(300),
                    ADD COLUMN IF NOT EXISTS estado_inmueble character varying(50),
                    ADD COLUMN IF NOT EXISTS id_scoring character varying(50),
                    ADD COLUMN IF NOT EXISTS tipo_inmueble character varying(50);

                ALTER TABLE public.carga_operacion_banco_datos_comercial
                    ADD COLUMN IF NOT EXISTS correo_declarativo_cliente character varying(150),
                    ADD COLUMN IF NOT EXISTS numero_telefono_declarativo character varying(20);

                ALTER TABLE public.carga_operacion_banco_antecedente_credito
                    ADD COLUMN IF NOT EXISTS aplica_cobertura boolean,
                    ADD COLUMN IF NOT EXISTS aplica_compra_cartera boolean,
                    ADD COLUMN IF NOT EXISTS aplica_fast_track boolean,
                    ADD COLUMN IF NOT EXISTS aplica_leasing boolean,
                    ADD COLUMN IF NOT EXISTS aplica_remodelacion boolean,
                    ADD COLUMN IF NOT EXISTS condiciones_organismo_decisor character varying(500),
                    ADD COLUMN IF NOT EXISTS fecha_aprobacion timestamp without time zone,
                    ADD COLUMN IF NOT EXISTS gente_bbva boolean,
                    ADD COLUMN IF NOT EXISTS id_tipo_sub_producto character varying(20),
                    ADD COLUMN IF NOT EXISTS monto_otorgado numeric(18,2);

                ALTER TABLE public.carga_operacion_banco_antecedente_comprador
                    ADD COLUMN IF NOT EXISTS celular character varying(20),
                    ADD COLUMN IF NOT EXISTS cliente_nomina boolean,
                    ADD COLUMN IF NOT EXISTS departamento character varying(50),
                    ADD COLUMN IF NOT EXISTS municipio character varying(50),
                    ADD COLUMN IF NOT EXISTS nombre_completo character varying(300),
                    ADD COLUMN IF NOT EXISTS numero_identificacion character varying(20),
                    ADD COLUMN IF NOT EXISTS situacion_laboral character varying(50),
                    ADD COLUMN IF NOT EXISTS tipo_documento_id character varying(10),
                    ADD COLUMN IF NOT EXISTS tipo_titular character varying(5);

                CREATE TABLE IF NOT EXISTS public.carta_aprobacion_bbva (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    id_expediente bigint NOT NULL,
                    id_tipo_sub_producto character varying(20) NOT NULL,
                    modelo_carta integer NOT NULL,
                    nombre_archivo_docx character varying(500),
                    nombre_archivo_pdf character varying(500),
                    url_docx character varying(1000),
                    url_pdf character varying(1000),
                    estado character varying(20) NOT NULL,
                    error_detalle text,
                    version integer NOT NULL,
                    is_active boolean NOT NULL,
                    row_status boolean NOT NULL,
                    created_by integer NOT NULL,
                    created_date timestamp without time zone NOT NULL,
                    modified_by integer,
                    modified_date timestamp without time zone,
                    CONSTRAINT "PK_carta_aprobacion_bbva" PRIMARY KEY (id)
                );

                CREATE TABLE IF NOT EXISTS public.registro_contacto_bbva (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    id_expediente bigint NOT NULL,
                    id_actividad character varying(50) NOT NULL,
                    id_usuario integer NOT NULL,
                    canal_contacto character varying(50) NOT NULL,
                    resultado_contacto character varying(50) NOT NULL,
                    observaciones text,
                    fecha_contacto timestamp without time zone NOT NULL,
                    is_active boolean NOT NULL,
                    row_status boolean NOT NULL,
                    created_by integer NOT NULL,
                    created_date timestamp without time zone NOT NULL,
                    modified_by integer,
                    modified_date timestamp without time zone,
                    CONSTRAINT "PK_registro_contacto_bbva" PRIMARY KEY (id)
                );

                CREATE TABLE IF NOT EXISTS public.validar_informacion_bbva (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    id_expediente bigint NOT NULL,
                    id_actividad character varying(50) NOT NULL,
                    tipo_id_t1 character varying(10),
                    numero_id_t1 character varying(20),
                    nombre_completo_t1 character varying(300),
                    celular_t1 character varying(20),
                    telefono_t1 character varying(20),
                    email_t1 character varying(150),
                    direccion_t1 character varying(300),
                    departamento_t1 character varying(50),
                    municipio_t1 character varying(50),
                    situacion_laboral_t1 character varying(50),
                    cliente_nomina_t1 boolean,
                    tipo_id_t2 character varying(10),
                    numero_id_t2 character varying(20),
                    nombre_completo_t2 character varying(300),
                    celular_t2 character varying(20),
                    email_t2 character varying(150),
                    tipo_id_t3 character varying(10),
                    numero_id_t3 character varying(20),
                    nombre_completo_t3 character varying(300),
                    celular_t3 character varying(20),
                    email_t3 character varying(150),
                    inmueble_definido boolean,
                    tipo_inmueble character varying(50),
                    estado_inmueble character varying(50),
                    constructora character varying(200),
                    es_constructora_vip boolean,
                    codigo_proyecto character varying(50),
                    descripcion_proyecto character varying(300),
                    departamento_inmueble character varying(50),
                    municipio_inmueble character varying(50),
                    estatus_general character varying(100),
                    requiere_definir_inmueble boolean,
                    requiere_carga_cliente boolean,
                    requiere_carga_constructora boolean,
                    tipo_credito character varying(50),
                    tiene_garantia boolean,
                    monto_otorgado_vi numeric(18,2),
                    correo_declarativo character varying(150),
                    telefono_declarativo character varying(20),
                    motivo_devolucion character varying(200),
                    observaciones character varying(500),
                    is_active boolean NOT NULL,
                    row_status boolean NOT NULL,
                    created_by integer NOT NULL,
                    created_date timestamp without time zone NOT NULL,
                    modified_by integer,
                    modified_date timestamp without time zone,
                    CONSTRAINT "PK_validar_informacion_bbva" PRIMARY KEY (id)
                );

                CREATE TABLE IF NOT EXISTS public.cargar_documentos_constructora (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    id_expediente bigint NOT NULL,
                    id_actividad character varying(100) NOT NULL,
                    avanzar_validar_documentos boolean NOT NULL,
                    observaciones text NOT NULL,
                    is_active boolean NOT NULL,
                    row_status boolean NOT NULL,
                    created_by integer NOT NULL,
                    created_date timestamp without time zone NOT NULL,
                    modified_by integer,
                    modified_date timestamp without time zone,
                    CONSTRAINT "PK_cargar_documentos_constructora" PRIMARY KEY (id)
                );

                CREATE INDEX IF NOT EXISTS "IX_cob_op_codigo_oficina"
                    ON public.carga_operacion_banco_datos_operacion (codigo_oficina);
                CREATE INDEX IF NOT EXISTS "IX_cob_op_id_scoring"
                    ON public.carga_operacion_banco_datos_operacion (id_scoring);
                CREATE INDEX IF NOT EXISTS "IX_cob_cred_subproducto"
                    ON public.carga_operacion_banco_antecedente_credito (id_tipo_sub_producto);
                CREATE INDEX IF NOT EXISTS "IX_cob_comp_numero_id"
                    ON public.carga_operacion_banco_antecedente_comprador (numero_identificacion);
                CREATE INDEX IF NOT EXISTS "IX_cob_comp_tipo_titular"
                    ON public.carga_operacion_banco_antecedente_comprador (id_expediente, tipo_titular);
                CREATE INDEX IF NOT EXISTS "IX_carta_aprobacion_expediente_estado"
                    ON public.carta_aprobacion_bbva (id_expediente, estado);
                CREATE INDEX IF NOT EXISTS "IX_registro_contacto_expediente"
                    ON public.registro_contacto_bbva (id_expediente, id_actividad);
                CREATE INDEX IF NOT EXISTS "IX_validar_info_expediente"
                    ON public.validar_informacion_bbva (id_expediente);
                CREATE INDEX IF NOT EXISTS idx_cdc_expediente
                    ON public.cargar_documentos_constructora (id_expediente);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "cargar_documentos_constructora");

            migrationBuilder.DropTable(
                name: "carta_aprobacion_bbva");

            migrationBuilder.DropTable(
                name: "registro_contacto_bbva");

            migrationBuilder.DropTable(
                name: "validar_informacion_bbva");

            migrationBuilder.DropIndex(
                name: "IX_cob_op_codigo_oficina",
                table: "carga_operacion_banco_datos_operacion");

            migrationBuilder.DropIndex(
                name: "IX_cob_op_id_scoring",
                table: "carga_operacion_banco_datos_operacion");

            migrationBuilder.DropIndex(
                name: "IX_cob_cred_subproducto",
                table: "carga_operacion_banco_antecedente_credito");

            migrationBuilder.DropIndex(
                name: "IX_cob_comp_numero_id",
                table: "carga_operacion_banco_antecedente_comprador");

            migrationBuilder.DropIndex(
                name: "IX_cob_comp_tipo_titular",
                table: "carga_operacion_banco_antecedente_comprador");

            migrationBuilder.DropColumn(
                name: "canal_originacion",
                table: "carga_operacion_banco_datos_operacion");

            migrationBuilder.DropColumn(
                name: "codigo_asesor",
                table: "carga_operacion_banco_datos_operacion");

            migrationBuilder.DropColumn(
                name: "codigo_oficina",
                table: "carga_operacion_banco_datos_operacion");

            migrationBuilder.DropColumn(
                name: "codigo_proyecto",
                table: "carga_operacion_banco_datos_operacion");

            migrationBuilder.DropColumn(
                name: "descripcion_oficina",
                table: "carga_operacion_banco_datos_operacion");

            migrationBuilder.DropColumn(
                name: "descripcion_proyecto",
                table: "carga_operacion_banco_datos_operacion");

            migrationBuilder.DropColumn(
                name: "estado_inmueble",
                table: "carga_operacion_banco_datos_operacion");

            migrationBuilder.DropColumn(
                name: "id_scoring",
                table: "carga_operacion_banco_datos_operacion");

            migrationBuilder.DropColumn(
                name: "tipo_inmueble",
                table: "carga_operacion_banco_datos_operacion");

            migrationBuilder.DropColumn(
                name: "correo_declarativo_cliente",
                table: "carga_operacion_banco_datos_comercial");

            migrationBuilder.DropColumn(
                name: "numero_telefono_declarativo",
                table: "carga_operacion_banco_datos_comercial");

            migrationBuilder.DropColumn(
                name: "aplica_cobertura",
                table: "carga_operacion_banco_antecedente_credito");

            migrationBuilder.DropColumn(
                name: "aplica_compra_cartera",
                table: "carga_operacion_banco_antecedente_credito");

            migrationBuilder.DropColumn(
                name: "aplica_fast_track",
                table: "carga_operacion_banco_antecedente_credito");

            migrationBuilder.DropColumn(
                name: "aplica_leasing",
                table: "carga_operacion_banco_antecedente_credito");

            migrationBuilder.DropColumn(
                name: "aplica_remodelacion",
                table: "carga_operacion_banco_antecedente_credito");

            migrationBuilder.DropColumn(
                name: "condiciones_organismo_decisor",
                table: "carga_operacion_banco_antecedente_credito");

            migrationBuilder.DropColumn(
                name: "fecha_aprobacion",
                table: "carga_operacion_banco_antecedente_credito");

            migrationBuilder.DropColumn(
                name: "gente_bbva",
                table: "carga_operacion_banco_antecedente_credito");

            migrationBuilder.DropColumn(
                name: "id_tipo_sub_producto",
                table: "carga_operacion_banco_antecedente_credito");

            migrationBuilder.DropColumn(
                name: "monto_otorgado",
                table: "carga_operacion_banco_antecedente_credito");

            migrationBuilder.DropColumn(
                name: "celular",
                table: "carga_operacion_banco_antecedente_comprador");

            migrationBuilder.DropColumn(
                name: "cliente_nomina",
                table: "carga_operacion_banco_antecedente_comprador");

            migrationBuilder.DropColumn(
                name: "departamento",
                table: "carga_operacion_banco_antecedente_comprador");

            migrationBuilder.DropColumn(
                name: "municipio",
                table: "carga_operacion_banco_antecedente_comprador");

            migrationBuilder.DropColumn(
                name: "nombre_completo",
                table: "carga_operacion_banco_antecedente_comprador");

            migrationBuilder.DropColumn(
                name: "numero_identificacion",
                table: "carga_operacion_banco_antecedente_comprador");

            migrationBuilder.DropColumn(
                name: "situacion_laboral",
                table: "carga_operacion_banco_antecedente_comprador");

            migrationBuilder.DropColumn(
                name: "tipo_documento_id",
                table: "carga_operacion_banco_antecedente_comprador");

            migrationBuilder.DropColumn(
                name: "tipo_titular",
                table: "carga_operacion_banco_antecedente_comprador");
        }
    }
}
