-- BBV-46 / BBV-49 - Objetos de aplicacion y catalogo.
--
-- Base destino: BBVA_LEGALIZACION.
--
-- Este script consolida los cambios manuales requeridos por:
--   BBV-46 - Cargar Documentos Cliente
--   BBV-49 - Cargar Soportes de Pago
--
-- No ejecutar en DBMFBBVA: esa base usa el script workflow xpdl_*.
-- Es idempotente: se puede ejecutar mas de una vez sin duplicar registros.

BEGIN;

CREATE TABLE IF NOT EXISTS public.cargar_documentos_cliente (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_expediente       BIGINT NOT NULL,
    id_actividad        VARCHAR(50) NOT NULL DEFAULT 'ACT_DOCS_CLIENTE',
    documentos_adjuntos BOOLEAN NOT NULL DEFAULT FALSE,
    observaciones       VARCHAR(500),
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    row_status          BOOLEAN NOT NULL DEFAULT TRUE,
    created_by          INTEGER NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    modified_by         INTEGER,
    modified_date       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT "PK_cargar_documentos_cliente" PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS "IX_cargar_docs_cliente_expediente"
    ON public.cargar_documentos_cliente(id_expediente);

CREATE TABLE IF NOT EXISTS public.cargar_soportes_pago (
    id                  BIGSERIAL PRIMARY KEY,
    id_expediente       BIGINT NOT NULL,
    id_actividad        VARCHAR(50) NOT NULL DEFAULT 'ACT_SOPORTES_PAGO',
    documentos_adjuntos BOOLEAN NOT NULL DEFAULT FALSE,
    observaciones       VARCHAR(500),
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    row_status          BOOLEAN NOT NULL DEFAULT TRUE,
    created_by          INTEGER NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    modified_by         INTEGER,
    modified_date       TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS "IX_cargar_soportes_pago_expediente"
    ON public.cargar_soportes_pago(id_expediente);

DO $$
DECLARE
    v_workflow_process_id CONSTANT varchar := '_yYE04AsMEeaJXe4_X2YDKw';
BEGIN
    IF to_regclass('public.cat_actividades_ws') IS NULL THEN
        RAISE EXCEPTION 'La tabla public.cat_actividades_ws no existe. Verifique que este script se ejecute en BBVA_LEGALIZACION.';
    END IF;

    INSERT INTO public.cat_actividades_ws (
        actividad,
        id_actividad,
        id_proceso,
        proceso,
        id_role,
        tipo,
        page,
        etapa,
        tiempo_promedio,
        is_active,
        row_status,
        created_by,
        created_date,
        modified_by,
        modified_date
    )
    SELECT
        seed.actividad,
        seed.id_actividad,
        seed.id_proceso,
        seed.proceso,
        seed.id_role,
        seed.tipo,
        seed.page,
        seed.etapa,
        NULL,
        TRUE,
        TRUE,
        'system',
        NOW(),
        NULL,
        NULL
    FROM (
        VALUES
            (
                'Cargar Documentos Cliente',
                'ACT_DOCS_CLIENTE',
                v_workflow_process_id,
                'Presto Legalizacion',
                4,
                'USUARIO',
                '/actividades/cargar-documentos-cliente',
                'Contacto Cliente'
            ),
            (
                'Cargar Soportes de Pago',
                'ACT_SOPORTES_PAGO',
                v_workflow_process_id,
                'Presto Legalizacion',
                4,
                'USUARIO',
                '/actividades/cargar-soportes-pago',
                'Contacto Cliente'
            )
    ) AS seed (
        actividad,
        id_actividad,
        id_proceso,
        proceso,
        id_role,
        tipo,
        page,
        etapa
    )
    WHERE NOT EXISTS (
        SELECT 1
        FROM public.cat_actividades_ws current_activity
        WHERE current_activity.id_actividad = seed.id_actividad
    );

    UPDATE public.cat_actividades_ws current_activity
    SET actividad = seed.actividad,
        id_proceso = seed.id_proceso,
        proceso = seed.proceso,
        id_role = seed.id_role,
        tipo = seed.tipo,
        page = seed.page,
        etapa = seed.etapa,
        is_active = TRUE,
        row_status = TRUE,
        modified_by = 'system',
        modified_date = NOW()
    FROM (
        VALUES
            (
                'Cargar Documentos Cliente',
                'ACT_DOCS_CLIENTE',
                v_workflow_process_id,
                'Presto Legalizacion',
                4,
                'USUARIO',
                '/actividades/cargar-documentos-cliente',
                'Contacto Cliente'
            ),
            (
                'Cargar Soportes de Pago',
                'ACT_SOPORTES_PAGO',
                v_workflow_process_id,
                'Presto Legalizacion',
                4,
                'USUARIO',
                '/actividades/cargar-soportes-pago',
                'Contacto Cliente'
            )
    ) AS seed (
        actividad,
        id_actividad,
        id_proceso,
        proceso,
        id_role,
        tipo,
        page,
        etapa
    )
    WHERE current_activity.id_actividad = seed.id_actividad;
END $$;

COMMIT;

-- Validaciones sugeridas despues de ejecutar:
--
-- SELECT to_regclass('public.cargar_documentos_cliente') AS cargar_documentos_cliente;
-- SELECT to_regclass('public.cargar_soportes_pago') AS cargar_soportes_pago;
--
-- SELECT id, id_actividad, actividad, id_role, page, etapa, is_active, row_status
-- FROM public.cat_actividades_ws
-- WHERE id_actividad IN ('ACT_DOCS_CLIENTE', 'ACT_SOPORTES_PAGO')
-- ORDER BY id_actividad;
