using Npgsql;

var sql = @"
CREATE TABLE IF NOT EXISTS public.entrega_documentos (
	id_entrega_documentos integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_expediente bigint NOT NULL,
	fecha_entrega timestamp without time zone NOT NULL,
	entregado_por character varying(200),
	recibido_por character varying(200),
	archivo_cargo character varying(500),
	observaciones character varying(1000),
	is_active boolean NOT NULL DEFAULT true,
	row_status boolean NOT NULL DEFAULT true,
	created_by integer NOT NULL DEFAULT 0,
	created_date timestamp without time zone NOT NULL DEFAULT now(),
	modified_by integer,
	modified_date timestamp without time zone
);

CREATE INDEX IF NOT EXISTS idx_entrega_documentos_id_expediente
ON public.entrega_documentos (id_expediente);

CREATE OR REPLACE FUNCTION public.usp_get_entrega_documentos_by_id_expediente(
	p_id_expediente bigint
)
RETURNS TABLE (
	id_entrega_documentos integer,
	id_expediente bigint,
	fecha_entrega timestamp without time zone,
	entregado_por character varying,
	recibido_por character varying,
	archivo_cargo character varying,
	observaciones character varying,
	is_active boolean,
	row_status boolean,
	created_by integer,
	created_date timestamp without time zone,
	modified_by integer,
	modified_date timestamp without time zone
)
LANGUAGE sql
AS $$
	SELECT
		ed.id_entrega_documentos,
		ed.id_expediente,
		ed.fecha_entrega,
		ed.entregado_por,
		ed.recibido_por,
		ed.archivo_cargo,
		ed.observaciones,
		ed.is_active,
		ed.row_status,
		ed.created_by,
		ed.created_date,
		ed.modified_by,
		ed.modified_date
	FROM public.entrega_documentos ed
	WHERE ed.id_expediente = p_id_expediente
	  AND ed.is_active = true
	  AND ed.row_status = true
	ORDER BY ed.id_entrega_documentos DESC
	LIMIT 1;
$$;

INSERT INTO public.cat_actividades_ws (
	actividad,
	id_actividad,
	id_proceso,
	id_role,
	page,
	is_active,
	row_status,
	created_by,
	created_date
)
SELECT
	'Entrega de Documentos',
	'_n3wED0CS4se5rV8QxL1tAa',
	'_yYE04AsMEeaJXe4_X2YDKw_CP',
	1,
	'entrega_documentos',
	true,
	true,
	'1',
	now()
WHERE NOT EXISTS (
	SELECT 1 FROM public.cat_actividades_ws
	WHERE id_actividad = '_n3wED0CS4se5rV8QxL1tAa'
);
";

var connectionStrings = new[]
{
	"Host=localhost;Port=5432;Database=multibanca;Username=multibanca;Password=multibanca123",
	"Host=localhost;Port=5432;Database=dbWFMultibanca;Username=postgres;Password=123"
};

foreach (var cs in connectionStrings)
{
	try
	{
		await using var conn = new NpgsqlConnection(cs);
		await conn.OpenAsync();

		await using (var cmd = new NpgsqlCommand(sql, conn))
		{
			await cmd.ExecuteNonQueryAsync();
		}

		await using (var verify = new NpgsqlCommand(@"
SELECT
  current_database() as db,
  to_regclass('public.entrega_documentos')::text as tabla,
  EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'usp_get_entrega_documentos_by_id_expediente') as funcion,
  EXISTS (SELECT 1 FROM public.cat_actividades_ws WHERE id_actividad = '_n3wED0CS4se5rV8QxL1tAa') as actividad;", conn))
		await using (var reader = await verify.ExecuteReaderAsync())
		{
			if (await reader.ReadAsync())
			{
				Console.WriteLine($"OK | DB={reader.GetString(0)} | TABLA={reader.GetString(1)} | FUNCION={reader.GetBoolean(2)} | ACTIVIDAD={reader.GetBoolean(3)}");
			}
		}
	}
	catch (Exception ex)
	{
		Console.WriteLine($"ERROR | {cs} | {ex.Message}");
	}
}
